# Generated by Django 3.2.7 on 2021-09-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAlimento', models.CharField(blank=True, max_length=100, null=True)),
                ('PrecioAlimento', models.FloatField(blank=True, max_length=7, null=True)),
                ('UnidadAlimento', models.CharField(blank=True, max_length=100, null=True)),
                ('CantidadAlimento', models.FloatField(blank=True, max_length=100, null=True)),
                ('Fotoalimento', models.ImageField(blank=True, null=True, upload_to='alimento')),
                ('FechaelaboracionAl', models.DateField(blank=True, null=True)),
                ('FechavencimientoAl', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artesanias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreArtesania', models.CharField(blank=True, max_length=100, null=True)),
                ('PrecioArtesania', models.FloatField(blank=True, max_length=7, null=True)),
                ('DescripcionArtesania', models.CharField(blank=True, max_length=500, null=True)),
                ('FotoArtesania', models.ImageField(blank=True, null=True, upload_to='artesania')),
            ],
        ),
        migrations.CreateModel(
            name='Carritocompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Organicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(blank=True, max_length=100, null=True)),
                ('PrecioProducto', models.FloatField(blank=True, max_length=7, null=True)),
                ('DescripcionProducto', models.CharField(blank=True, max_length=500, null=True)),
                ('FotoProducto', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('FechaelaboracionPR', models.DateField(blank=True, null=True)),
                ('FechavencimientoPR', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentos', models.ManyToManyField(to='comercio.Alimentos')),
                ('artesanias', models.ManyToManyField(to='comercio.Artesanias')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.carritocompras')),
                ('productos', models.ManyToManyField(to='comercio.Productos_Organicos')),
            ],
        ),
    ]
