<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-14 02:02

from django.db import migrations, models
=======
# Generated by Django 3.2.7 on 2021-09-10 02:38

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 09000cce4ff81a7d9a4bd6d28a0c55388595946b


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAlimento', models.CharField(blank=True, max_length=100, null=True)),
                ('PrecioAlimento', models.FloatField(blank=True, max_length=7, null=True)),
                ('UnidadAlimento', models.CharField(blank=True, max_length=100, null=True)),
                ('CantidadAlimento', models.FloatField(blank=True, max_length=100, null=True)),
                ('Fotoalimento', models.ImageField(blank=True, null=True, upload_to='alimento')),
                ('FechaelaboracionAl', models.DateField(blank=True, null=True)),
                ('FechavencimientoAl', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artesanias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreArtesania', models.CharField(blank=True, max_length=100, null=True)),
                ('PrecioArtesania', models.FloatField(blank=True, max_length=7, null=True)),
                ('DescripcionArtesania', models.CharField(blank=True, max_length=500, null=True)),
                ('FotoArtesania', models.ImageField(blank=True, null=True, upload_to='artesania')),
            ],
        ),
        migrations.CreateModel(
            name='Carritocompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCarrito', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Organicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(blank=True, max_length=100, null=True)),
                ('PrecioProducto', models.FloatField(blank=True, max_length=7, null=True)),
                ('DescripcionProducto', models.CharField(blank=True, max_length=500, null=True)),
                ('FotoProducto', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('FechaelaboracionPR', models.DateField(blank=True, null=True)),
                ('FechavencimientoPR', models.DateField(blank=True, null=True)),
            ],
        ),
=======
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='')),
                ('fechacreacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carritocompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombreartista', models.CharField(max_length=100, primary_key=1, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivoaudio', models.FileField(blank=True, null=True, upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.musico'),
        ),
>>>>>>> 09000cce4ff81a7d9a4bd6d28a0c55388595946b
    ]
