# Generated by Django 3.2.7 on 2021-09-10 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='')),
                ('fechacreacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carritocompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombreartista', models.CharField(max_length=100, primary_key=1, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivoaudio', models.FileField(blank=True, null=True, upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.musico'),
        ),
    ]
