# Generated by Django 3.2.7 on 2021-09-14 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritocompras',
            old_name='NombreCarrito',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentos', models.ManyToManyField(to='comercio.Alimentos')),
                ('artesanias', models.ManyToManyField(to='comercio.Artesanias')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.carritocompras')),
                ('productos', models.ManyToManyField(to='comercio.Productos_Organicos')),
            ],
        ),
    ]
