# Generated by Django 3.2.7 on 2021-09-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_alimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_Organicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(blank=True, max_length=100, null=True)),
                ('PrecioProducto', models.FloatField(blank=True, max_length=7, null=True)),
                ('FotoProducto', models.ImageField(blank=True, null=True, upload_to='')),
                ('FechaelaboracionPR', models.DateField(blank=True, null=True)),
                ('FechavencimientoPR', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='canciones',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='canciones',
        ),
        migrations.DeleteModel(
            name='Musico',
        ),
    ]
