# Generated by Django 3.2.7 on 2021-09-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0004_artesanias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='Fotoalimento',
            field=models.ImageField(blank=True, null=True, upload_to='alimento'),
        ),
        migrations.AlterField(
            model_name='artesanias',
            name='FotoArtesania',
            field=models.ImageField(blank=True, null=True, upload_to='artesania'),
        ),
        migrations.AlterField(
            model_name='productos_organicos',
            name='FotoProducto',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
    ]
