# Generated by Django 3.2.7 on 2021-09-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0005_auto_20210910_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesanias',
            name='RegionArtesania',
        ),
        migrations.AddField(
            model_name='alimentos',
            name='CantidadAlimento',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='UnidadAlimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artesanias',
            name='DescripcionArtesania',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productos_organicos',
            name='DescripcionProducto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
