# Generated by Django 3.2.7 on 2021-09-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artesanal', '0001_initial'),
        ('Alimentos', '0001_initial'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carritocompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frutas', models.ManyToManyField(to='Alimentos.frutas')),
                ('Hogar', models.ManyToManyField(to='Productos.hogar')),
                ('Personal', models.ManyToManyField(to='Productos.personal')),
                ('Postres', models.ManyToManyField(to='Alimentos.postres')),
                ('Salud', models.ManyToManyField(to='Productos.saludybelleza')),
                ('Verduras', models.ManyToManyField(to='Alimentos.verduras')),
                ('alimentos', models.ManyToManyField(to='Alimentos.alimento')),
                ('artesanias', models.ManyToManyField(to='Artesanal.Artesanias')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.carritocompras')),
                ('otros', models.ManyToManyField(to='Artesanal.Otros')),
                ('ropa', models.ManyToManyField(to='Artesanal.Ropa')),
                ('veganos', models.ManyToManyField(to='Alimentos.vegano')),
            ],
        ),
    ]
