# Generated by Django 3.2.7 on 2021-09-11 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.FloatField(default=0)),
                ('usuarios', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='productoscom',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=0)),
                ('categoria', models.CharField(choices=[('Mujer', 'm'), ('Hombre', 'h')], max_length=100)),
                ('cod_barras', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkout.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkout.productoscom')),
            ],
        ),
    ]
