# Generated by Django 3.2.7 on 2021-09-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('Precio', models.FloatField(blank=True, max_length=7, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('Unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('Cantidad', models.FloatField(blank=True, max_length=100, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('Fechaelaboracion', models.DateField(blank=True, null=True)),
                ('Fechavencimiento', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.categoria')),
            ],
        ),
    ]
