# Generated by Django 3.0.8 on 2021-10-05 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productosartesanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Precio', models.FloatField(max_length=7)),
                ('Descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.FloatField()),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('descuento', models.FloatField()),
                ('Lugarelaboracion', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artesanal.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=500, null=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artesanal.Productosartesanal')),
            ],
        ),
    ]
